### ISSUE TITLE
Develop Kaidan!

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#1]
Here will be explained how and with which libraries Kaiwa should be developed. If you have any suggestions, please post them under this issue.
## Back-End

The technical part should be made in C++ with the XMPP library Swiften (3.0, later 4.0) (Swift is the client, Swiften is the library). It is well maintained, because they have hired someone. So I see here the best chances for the future.
#### Links

https://github.com/swift/swift
http://swift.im/swiften.html
## GUI

The GUI should be written in Qt Quick (QML), Qt Quick Controls (soon Qt Quick Controls 2) and Kirigami.
Kirigami should be used for the most of elements, but simple things like buttons should be made with Qt Quick Controls.
#### Links

http://wiki.qt.io/Category:Developing_with_Qt::Qt_Quick
http://doc.qt.io/qt-5/qtquickcontrols-index.html
https://techbase.kde.org/Kirigami
#### KEmoticons

KEmoticons could be used to convert emoticons from text to a graphical representation.
https://api.kde.org/frameworks/kemoticons/html/
## All dependencies

`swiften` `qt5` `qtquick` `qtquickcontrols` `kirigami` maybe: `KEmoticons`
## (probably) Supported Platforms
- Linux Desktop (x11 and wayland)
- Jolla
- Sailfish OS
- Plasma Mobile
- Android
- iOS (when Qt supports it)
- OS X
- Windows

That's quiet much! But easy realizable with qt quick.

**Comment by MRZA-MRZA** [comment]
Isn't wiki the better place for this info?

**Comment by LNJ2** [comment]
@MRZA-MRZA Surely, but we don't have a wiki!

**Comment by LNJ2** [comment]
Oh  ...  you mean the GitHub wiki. Yeah that's a better Idea! :+1:

**Comment by LNJ2** [comment]
Moved into the gh wiki: https://github.com/KaidanIM/Kaidan/wiki/Development-Overview
