### ISSUE TITLE
Clean up project structure

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#10]
I have to say I don't like the structure as it is, now.
The `app` folder is unnecessary, because everything else should probably also belong to `app`. And I also don't like it to first have to `cd app/` and only do `qmake ; make`, instead of directly do `qmake ; make`.

However I would suggest this structure:
* `bin` - Binaries (should be created after building)
* `doc` - Documentation / Licenses
    * `license_gpl-3.0.txt`
    * `license_cc_by-sa-4.0.txt`
* `src` - Source Code
    * `qml` QML-files
        * `*.qml`
    * `*.cpp` `*.h`
* `data`
    * `images`
        * `*.png` `*.svg`
    * `sounds`
        * `*.opus` `*.flac`
    * `fonts`
        * `*.ttf`
* `util` - Utilities (travis-ci scripts, deb/rpm package files, ...)
* `misc` - Miscellaneous (for logos, .desktop-files, ...)
* `README.md`
* `LICENSE.txt`
* `kaidan.pro`
* `kaidan.qrc`
* `deployment.pri`

I also like [this](https://github.com/KDE/discover) structure, but I think the one above might be better for our project.

What do you think about this?

**Comment by geobra** [comment]
The reason for the app folder is the possibility to have a test folder besides the app folder. Test shouldn't go on the same level as the app itself. So in my opinion, the folder structure should look like this:
app
  bin
  doc
  src
  data (or resource)
  deb
  rpm
  kaidan.pro
test
  1 to n folders with tests
util (travis, ...)
  ...

readme.md
license.txt
...

**Comment by LNJ2** [comment]
@geobra Why do you need test folders? Which tests? Any tests can be outside this repo, can't they?

**Comment by geobra** [comment]
Now I got your point. Of course we can put the tests outside of kaidan repo. If we go this way then your initial suggestion of the repo structure is ok for me.

**Comment by LNJ2** [comment]
@geobra So can I make a PR for it (when I've successfully built the project)?

**Comment by geobra** [comment]
You are welcome to do this.
