### ISSUE TITLE
ChatPage: Show date/time of messages

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#103]

**Comment by JBBgameich** [comment]
(Speaking also for issue  https://github.com/KaidanIM/Kaidan/issues/104)
As you know, I'm already working on that, and only experienced a few problems with
* automatic message background (rectangle) resizing
* Displaying the checkmark icon without adding a new dependency, which would probably need updating to kirigami 2.2 in our repo.

**Comment by LNJ2** [comment]
* 1: first do the design of the message itself, then I can try to help you.
* 2: Kirigami 2 is not in stretch at all, so no matter if we depend on Kirigami 2.0 or 2.2 (we just have to update the packages ...)
