### ISSUE TITLE
RosterPage: Improve design and display lastMessage

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#111]

**Comment by JBBgameich** [comment]
As you know, I'm already working on that, and only experienced a few problems with
* automatic message background (rectangle )resizing
* Displaying the checkmark icon without adding a new dependency, which would probably need updating to kirigami 2.2 in our repo.

**Comment by LNJ2** [comment]
As you probably don't know: this is the wrong issue. :rofl:

**Comment by LNJ2** [comment]
https://github.com/KaidanIM/Kaidan/commit/1a951c1b451789a8cc336c31d7bdd339956819db
