### ISSUE TITLE
Improve In-Chat page to make it useable.

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#13]
(This issue is just for the milestone)

Here is a good tutorial for the chat page in QtQuick Controls 2:
http://doc.qt.io/qt-5/qtquickcontrols2-chattutorial-example.html

We just need to port it to kirigami.

**Comment by MRZA-MRZA** [comment]
I tried it but Qt Creator says that Page component (https://doc.qt.io/qt-5/qml-qtquick-controls2-page.html) is not found. Do I need Qt 5.7 to use it?

**Comment by LNJ2** [comment]
@MRZA-MRZA It's with qtquickcontrols2, so Idk maybe you need even Qt 5.8

**Comment by MRZA-MRZA** [comment]
I have Qt 5.6.1 installed (latest available in Ubuntu). There should be Page component (https://doc.qt.io/qt-5.6/qmltypes.html#p). But I get not found error when I try to use Page.

**Comment by LNJ2** [comment]
@MRZA-MRZA It might be because this tutorial uses the new qtquickcontrols2, and not qtquickcontrols.

**Comment by MRZA-MRZA** [comment]
@LNJ2 It's just because Qt 5.6 provides Page element only in Qt.labs.controls which is not available in Ubuntu.

**Comment by JBBgameich** [comment]
On KDE Neon I already have Qt 5.8, maybe you could use Neon for developenment in a virtual machine or as dual boot, or just add the apt sources which are ubuntu compatible [neon.kde.org](neon.kde.org)
![spectacle l26736](https://cloud.githubusercontent.com/assets/13609393/20365850/ddf2a84a-ac48-11e6-828e-76d9e427afcf.png)

**Comment by LNJ2** [comment]
@JBBgameich 
> I already have Qt 5.8, ...

5.7?

**Comment by JBBgameich** [comment]
You're right, just mixed up the kde frameworks version, which is not important for us, with the Qt version.
