### ISSUE TITLE
AppImage: Resource files are not found

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#141]
The AppImage is currently only working correctly, with an kaidan installation ... so the AppImage is currently nearly useless...
![image_2017-11-22_20-03-16](https://user-images.githubusercontent.com/13557034/33148293-9322e1f2-cfcb-11e7-9e5d-028fef3ccc12.png)
![photo_2017-11-22_21-22-21](https://user-images.githubusercontent.com/13557034/33148308-a2c7d838-cfcb-11e7-836f-e77a05484818.jpg)

**Comment by JBBgameich** [comment]
It's most likely a problem with getResourcePath. QStandardPaths still seems to use the pathes of the host system. I'll ask in the AppImage group for ideas on how to fix this soon.

**Comment by probonopd** [comment]
How can the issue be reproduced?
It asks me for a Jabber account, but I don't have. It also doesn't say where to get one.

**Comment by probonopd** [comment]
Also, this seems wrong:

https://github.com/KaidanIM/Kaidan/blob/cd8ed274ca5df6b2d135dbfb6a8e7db6989bd381/utils/AppImage.sh#L17

Please try instead:

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
make -j$(nproc)
make DESTDIR=../AppDir -j$(nproc) install ; find ../AppDir
```

as per https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

**Comment by JBBgameich** [comment]
Jabber / XMPP is decentralized, so you can use different servers like xmpp.jp, jabber.de and some diaspora* servers. After you logged in, you'll directly see the issue of all images missing.

**Comment by JBBgameich** [comment]
The current AppImage.sh script is tested and works apart from not finding ressources. The images are successful included in the AppImage, but aren't found (probably) because of QStandardPaths not knowing the locations inside the AppImage.

**Comment by probonopd** [comment]
Are we talking about these?

```
usr/share/kaidan/images/banner.png
usr/share/kaidan/images/chat.png
usr/share/kaidan/images/diaspora.svg
usr/share/kaidan/images/fallback-avatar.svg
usr/share/kaidan/images/kaidan.svg
usr/share/kaidan/images/message_checkmark.svg
usr/share/kaidan/images/xmpp.svg
```

**Comment by JBBgameich** [comment]
yes, that are the relevant files.

**Comment by probonopd** [comment]
Interesting issue indeed. You are using `QStringList QStandardPaths::standardLocations(QStandardPaths::AppDataLocation);`

https://github.com/KaidanIM/Kaidan/blob/2b30286e02680e4058165fbc59d072ebd96dd84a/src/Kaidan.cpp#L285

According to the Qt documentation, this resolves to `"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"` but clearly `/usr` is not where these things are located in an AppImage.

You could use[ `QString QCoreApplication::applicationFilePath()`](http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath) instead and construct a _relative_ path to `../share/kaidan/images/` from there.

As a result, it should work both in normal installations and in relocatable installations such as AppImages.

**Comment by LNJ2** [comment]
@probonopd Thanks for your help! :smiley: :+1:
