### ISSUE TITLE
TLS Connection is always failing on release builds

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#147]
This includes the current AppImage .. :neutral_face:

**Comment by JBBgameich** [comment]
As it works on my machine again, I'll try rebuilding the AppImage.

**Comment by LNJ2** [comment]
@JBBgameich 👍

**Comment by LNJ2** [comment]
It's always happening on release builds...

**Comment by JBBgameich** [comment]
I uploaded a new AppImage built in Debug mode. Happy testing!
