### ISSUE TITLE
Move or hide the drawer grab button on the chat page

### ISSUE THREAD

**Issue by IlyaBizyaev** [KaidanIM/Kaidan#152]
![spectacle pe7721](https://user-images.githubusercontent.com/11175213/34071751-70f9f01a-e28c-11e7-8906-61164ddc98fa.png)

**Comment by LNJ2** [comment]
We could add a mouse area on the contact page and only make the drawer button visible, when you hover the mouse over the contact page or the contact page is active.

**Comment by LNJ2** [comment]
This was fixed in bfb720ab3d3bcaecf7377cc63bb0ff043018f5f6 (#179)
