### ISSUE TITLE
Contact delete button looks through the list item

### ISSUE THREAD

**Issue by IlyaBizyaev** [KaidanIM/Kaidan#153]
It should be deactivated when not visible

**Comment by LNJ2** [comment]
@IlyaBizyaev I haven't noticed that till I used kaidan on android.

**Comment by LNJ2** [comment]
It also blocks the space of the content:
![image](https://user-images.githubusercontent.com/13557034/36791914-4f85168e-1c99-11e8-889d-e1d42f35c145.png)

**Comment by IlyaBizyaev** [comment]
@LNJ2 Could you add this to the Kirigami bug report?
