### ISSUE TITLE
Avoid the use of buttons

### ISSUE THREAD

**Issue by IlyaBizyaev** [KaidanIM/Kaidan#154]
This is one of the UI refinements I think is necessary to give Kaidan a modern, clean look.

My friend told me that buttons are somewhat ugly. At first, I couldn't get what he thinks is wrong about them, but then I understood that generic rectangular buttons are no longer expected on mobile (and convergent) interfaces. Like, there are cases when the use of old style buttons is necessary, but usually they are avoided. As of current Kaidan's UI:

- [x] Close button on the About page is not needed - it's not a dialog, rather one of the pages, there's no need to close it.
- [ ] On the login screen, we need a circular and/or flat button with an icon
- [x] For the messages, "Send" is never used these days; I wrote to a Breeze icons chat and requested a generic "send" icon

**Comment by LNJ2** [comment]
We don't have acircular and/or flat button with an icon, but I think how it is currently is absolutely fine. So I'll close this (reopen if you think differently).
