### ISSUE TITLE
Make AddContact a RosterPage Action

### ISSUE THREAD

**Issue by IlyaBizyaev** [KaidanIM/Kaidan#155]
The drawer structure does not reflect users' intentions. Roster page is not listed in drawer, while adding contacts (seldom needed) is.

What I suggest is to add roster page to the drawer and make adding a new contact a roster page action.

**Comment by JBBgameich** [comment]
We have just been copying Telegrams structure and design, but this is not compliant with Kirigami's HIG.

**Comment by IlyaBizyaev** [comment]
Also, this solves a bug with the "Add contact" dialog being invisible when adding a contact is triggered from any page rather then roster.

**Comment by LNJ2** [comment]
👍 for making the new contact a roster action.
But as long as we don't have separated lists for contacts and chats there's no need to add the roster page to the global drawer.

**Comment by IlyaBizyaev** [comment]
There actually is :)
If there's no close button on the "About" page, it is impossible to get to the roster on mobile :)

**Comment by LNJ2** [comment]
You can just swipe to the left.

**Comment by IlyaBizyaev** [comment]
Not a known gesture unless you're really familiar with Kirigami :P

**Comment by LNJ2** [comment]
I don't think the gesture is so special, e.g. Telegram also has it. And if you don't understand this, you can still just press the back button, which every user should be familiar with.

**Comment by IlyaBizyaev** [comment]
Still, despite being removed from many apps recently, drawer is a well known concept representing application structure. So, we want it to really represent what Kaidan has to offer. I frankly failed to return to the roster not pressing the close button, even though I knew Kirigami has gestures. The back button was unexpected as it is usually used in stack structures and is emphasized with a back arrow at the top in MD.
Here, we want a simple top-level structure. Also, separating contact and message lists is a question of time, so we'll need to add roster page to the drawer anyway.

**Comment by LNJ2** [comment]
Yeah, we'll have to add the roster page to the drawer anyway, but we don't need to add the chat list page then.

**Comment by IlyaBizyaev** [comment]
So, if we'll have contact and chat lists, we'll only add one of them to the drawer?
