### ISSUE TITLE
Coding style: tabs or blanks?

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#17]
I would vote for using hard tabs, (size 8).
@MRZA-MRZA @geobra What do you like?

**Comment by MRZA-MRZA** [comment]
I use tabs (I hate spaces).

**Comment by JBBgameich** [comment]
I vote for tabs too, simply because I used them in history and would like to continue.

**Comment by LNJ2** [comment]
We use hard tabs, now.
