### ISSUE TITLE
Don't save password in plaintext

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#174]
https://wiki.qt.io/Simple_encryption_with_SimpleCrypt

**Comment by ata2001** [comment]
What's wrong with storing passwords in plaintext?

**Comment by LNJ2** [comment]
If you don't encrypt your disk or just let other users on your system see your files, they can really easily get your passwords, without needing to know anything, they just go into ~/.config/kaidan/ and see the kaidan.conf and can access the password in it. - You usually don't want that to happen.

**Comment by ata2001** [comment]
@LNJ2 Why would I let other users access my Kaidan config file? It's right in my home dir, no one besides me can read it, even without selinux.

If you meant to implement master key based password management, I would recommend providing integration with external password managers, or at least choosing a better encryption algorithm than SimpleCrypt.

From the wiki page you linked:

> The class presented in this article does not provide strong encryption!

> It will protect your data from casual observers, but it will not stand up to dedicated hackers trying to break your secrets. I am not a cryptography expert. Use the code here at your own risk. I am not to be held responsible for any damages that may, directly or indirectly, happen because of your use of this code. Don't say you were not warned.

**Comment by LNJ2** [comment]
Well, it doesn't have to provide strong encryption. It is just for the purpose that you don't accidently leak your password, when someone sees e.g. your opened config file. It's a large difference between plaintext and very simple encryption in this case.

**Comment by ata2001** [comment]
That's not a reason to call it encryption, and give a false sense of security. If you store the passwords in another file, others won't accidentally see your passwords, because you'll only have the regular config file open in your text editor.

To be honest, I believe there is no sane use case for a "weak" encryption, that can be cracked by "dedicated hackers trying to break your secrets" in any software.

**Comment by LNJ2** [comment]
I'm not saying it's strongly encrypted and no one can break it (what is actually not possible, without using an OTP), I only say it's not in plaintext.

**Comment by ata2001** [comment]
plaintext > bad security

If your goal is only to hide it, you could just put it in a different file. Something like this only adds an unnecessary layer of complexity/obscurity.

**Comment by LNJ2** [comment]
@JBBgameich suggested to use base64, I think that would be sufficient.

**Comment by ata2001** [comment]
@LNJ2 I still don't see the point, but yeah, base64 would be much better, because it won't get confused with secure encryption, and it's simple, I'll be able to change the password manually.
