### ISSUE TITLE
Use CMake

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#18]
Just some notes (more or less for me):

### Swiften cmake module (I've found on github)
https://github.com/hanzz/spectrum2/blob/master/cmake_modules/SwiftenConfig.cmake

### kirigami git repo (with cmake scripts)
https://cgit.kde.org/kirigami.git/tree/README.md

This should make it easier to build apks with kirigami and to find packages like swiften. (I'm not satisfied with the current solution)

**Comment by geobra** [comment]
Swiften uses scons. Maybee this is also an option for a new build system to use. Keep in mind that it must be integrated into qtcreator.

**Comment by MRZA-MRZA** [comment]
Can't we use autotools as a sane alternative?

**Comment by LNJ2** [comment]
@MRZA-MRZA If you think that this is easier, yes why not.
@geobra I don't really know scons. Maybe.

But I think CMake is the easiest one (at least for me), because there exist scripts for all libraries, kirigami uses it to build apks for android and I have already worked with it.

and @geobra I'm sure there is a quick way to execute the cmake script via. qmake.
