### ISSUE TITLE
Fix icon is transparent instead of white partly

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#181]
Currently the icon only looks good on white background, because parts of it are transparent instead of white.

**Comment by IlyaBizyaev** [comment]
Fixed by the new logo (3457a811bd067dd038feae7a3e919071d87d0ecf)
![final](https://user-images.githubusercontent.com/11175213/36634070-1d1e0976-19b0-11e8-9faa-4dab9ebda9eb.png)
