### ISSUE TITLE
No indication of invalid account credentials on connect

### ISSUE THREAD

**Issue by ge0rg** [KaidanIM/Kaidan#216]
Affected version: 0.3.2+git20180322-1 from Debian repo.

Steps to reproduce:
1. Start kaidan
2. Enter incorrect credentials
3. Press [Connect]

Expected result:
* UI indication of what went wrong

Observed reesult:
* [Connect] button changes to [Connecting...] for a moment, then back to [Connect]
* Console shows this line, among others:

`[client] Disconnected: Enums::DisconnectionReason(ConnAuthenticationFailed)`

**Comment by LNJ2** [comment]
This is still not implemented, but good to see an issue for this. Actually only some simple UI is missing.

**Comment by JBBgameich** [comment]
A new build with this feature implemented has been pushed to the apt repository.
