### ISSUE TITLE
Inconsistent name shortening in Contacts tab

### ISSUE THREAD

**Issue by ge0rg** [KaidanIM/Kaidan#217]
Long names are abbreviated with "..." after some letters. However, the amount of visible text does not match the width of the Contacts tab, and the number of letters / width is inconsisten for different contacts. While some names are cut off after four characters ("Simo..." for "Simon Lastname"), other names have as many as 14 characters shown.

**Comment by JBBgameich** [comment]
This bug is already known and is probably an upstream bug in Kirigami, the QML library we're using for most parts of the interface. I'll forward the bug report to the Kirigami developers.
