### ISSUE TITLE
Coding style for C++ and QML

### ISSUE THREAD

**Issue by MRZA-MRZA** [KaidanIM/Kaidan#23]
What coding style should be used in Kaidan?
I prefer the following:
```
char *s;
int main(){
    if(statement){
        m = x*2 + n;
        somefunc();
    }
}
```
The same applies to QML/JS.
What's your opinion? I believe I can tune preference in Qt Creator to mach project's coding style.

**Comment by LNJ2** [comment]
```c++
int theBestNumber = 42;
int main()
{
        if(theBestNumber == 42)
        {
                int xyz = 1234;
                hui();
        }
}
```

or, when it should be shorter:
```c++
if(theBestNumber == 42) {
        hui();
}
```
(there is a blank between `)` and `{`)

<br /><br />

I don't like this style:
```c++
if(theBestNumber == 42){
```
(without the blank)
