### ISSUE TITLE
Add ability to logout

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#25]

**Comment by JBBgameich** [comment]
How do we want to store account data? The jid could be stored in plaintext, but this is not acceptable for passwords

**Comment by LNJ2** [comment]
@JBBgameich 
With #54 the passwords will be stored in plain text and there is no settings page: Kaidan will only ask you for a password on disconnection (/ connection failure). Changing this should be done in another PR.

**Comment by JBBgameich** [comment]
This is just a ui question, right? I will work on adding a kirigami drawer which could contain the logout button.

**Comment by LNJ2** [comment]
@JBBgameich You already have an open PR for that, use this (I updated it just now :D)
