### ISSUE TITLE
Add Kaidan icon

### ISSUE THREAD

**Issue by LNJ2** [KaidanIM/Kaidan#27]

**Comment by JBBgameich** [comment]
I already thouhgt about this and have a few ideas:

- we could use an icon similar to conversations: ![](https://conversations.im/images/conversations_logo.png)

- because the word kaidan is japanese, we could use the japanese Kanji or hiragana

 # か

- maybe something from the Qt logo, so you see it's made with Qt

**Comment by LNJ2** [comment]
# シ　ツ

Maybe better one of these. They look like smileys. :D
@JBBgameich That would be the real kanjis: 会話 I don't like to only use the first letter (か).

**Comment by MRZA-MRZA** [comment]
@JBBgameich I like your icon! Maybe make it glossy?

**Comment by LNJ2** [comment]
@JBBgameich (ahh and I forgot to say:) I also like the general style of your icon! :+1: :smiley:

**Comment by JBBgameich** [comment]
@MRZA-MRZA I will play around with inkscape effects a bit and show the result here.

@LNJ2 Would シ　ツ make any sense? Katakana shi and tsu look nice, but then i like the か better. And whats wrong with dropbox? It's just that you can get the original file, and I get direct links there. By the way I corrected the link to be direct.

**Comment by JBBgameich** [comment]
I started trying out the effects and filters:

## 1. try
![logo_variant_1](https://cloud.githubusercontent.com/assets/13609393/20461415/f821522c-aefd-11e6-9083-d33e44f57562.png)
https://gist.github.com/JBBgameich/44c3404bfcc5a52961ba62217dc5c90a
https://dl.dropboxusercontent.com/s/xpt3yy6hbu7vg0l/kaidan_variant_1.svg

## 2. try
A more colorful one
![logo_variant_2](https://cloud.githubusercontent.com/assets/13609393/20461517/090eed3a-af01-11e6-8de5-3d3b05d00903.png)
https://dl.dropboxusercontent.com/s/ax6blf8l2opc2ub/kaidan_variant_2.svg
https://paste.kde.org/ptxwfuzns

You can try editing filters, colours, japanese character ... of course, if we all like one let's set it as our organization icon.

**Comment by LNJ2** [comment]
@JBBgameich 
> Would シ　ツ make any sense?

Would make か any sense?
Only か can stand for anything, there are 100+ kanjis that can be read with か - 'ka'. E.g. 火 / か / fire or 火曜日 / かようび / Tuesday/fire-day or 漢字/かんじ/kanji ... you can add here hundreds of words...

シ or ツ look like smileys so everyone can "understand" them as smileys and they don't look too complicated (as the kanjis for kaidan would look like [会談]).

**Comment by JBBgameich** [comment]
I will make an example variant with ツ

**Comment by MRZA-MRZA** [comment]
@JBBgameich I like the first variant. MB emphasize a silhouette of か?

**Comment by geobra** [comment]
I really like the one's with the smiley. The other ones remind me of 'hacked and imported' chines smart phones which doesn't get an i18n...

**Comment by geobra** [comment]
And what about a smooth circle in the top left instead of the edge? At least on sailfish every icon has a circle somewhere.

**Comment by JBBgameich** [comment]
You can try editing with inkscape ... If it looks better we can use it. I copied this style from the qt logo.

**Comment by IlyaBizyaev** [comment]
**Hello!** :smiley: 
I have an idea for the Kaidan project - not sure if you'll like it, but still decided to share.

In my opinion, the name _Kaidan_ is not quite easy to remember, which makes it more difficult for the project to succeed. So, I decided to make up another name :)
My idea is _Kstati_ (or _Kstaty_). This word is the transliteration of the Russian word "Кстати", which means "By the way".
Here is my vector logo:
![path3142-3](https://cloud.githubusercontent.com/assets/11175213/20859742/44dda9ce-b978-11e6-9457-3fce7f67309d.png)
Here is the SVG source: 
[Kstati.svg.zip](https://github.com/KaidanIM/Kaidan/files/628888/Kstati.svg.zip)

Hope you'll like it :relaxed:

**Comment by LNJ2** [comment]
Welcome @IlyaBizyaev! :smiley: 

The icon looks cool! :+1: 
But I don't understand why there is a comma? With _this_ blue it looks a bit like Telegram.. but that would ok, I think. The shadow looks a bit cropped at the bottom and on the right.

I think the name of this project is good so, it is Japanese and stands for 'conversation(s)' or 'conference(s)' :D
Two of us ( @JBBgameich and I) are learning Japanese and like the country, because of this we want to have a small "Japanese-touch" in our application. Maybe it's not so easy for you to remember the name, because you're not so familiar with Japanese / you come from Russia. That's different for us (from Germany), here Kaidan could be a normal German word and is not too "special".

I think I would have the same problems with "Kstati" as you with "Kaidan". And for people from Germany (and some other countries) it's very hard to pronounce three consonants (kst) one behind the other. When I try to read it, I either add another vowel somewhere, or I say _K-Staty_, which is actually the same.

But I like your icon! I personally just would change the coulor and replace the 'K' with a 'ツ'. :smile_cat:

**Comment by IlyaBizyaev** [comment]
The comma actually represents the idea, as there is always a comma after the Russian word "Кстати".
As for the details you've mentioned, I agree that the icon is imperfect: it is just a concept, not the final design.
I have totally forgotten that it can be difficult to pronounce Russian words :D
I recommend you to use Google Translate to listen to the pronunciation - maybe it's not as difficult as you think.
Anyway, I like the name Kaidan, and will definitely follow your progress :)
I am grateful for your review, and I'm so glad you like my icon (^_^)

**Comment by LNJ2** [comment]
> The comma actually represents the idea, as there is always a comma after the Russian word "Кстати".

Okay, that makes sense, of course. :D

> I recommend you to use Google Translate to listen to the pronunciation

Yeah, google translate helps, but I still couldn't talk to somebody about it without interruptions/pronouncing it wrongly.

> Anyway, I like the name Kaidan, and will definitely follow your progress :)

That's nice to hear! :)
We're just not the fastest... but we work on it.

**Comment by JBBgameich** [comment]
@IlyaBizyaev As I said on telegram already, I like your icon too! I probably like it even more then my own ones! You maybe could just make a variant with this smiley like japanese character "ツ". I just don't know which to choose after so many ones to choose from :D What about doing an icon competition where everybody can post his final icon for the first relase e.g. until next weekend, and we make a poll. I would like to use the icon for my next pull-request, so I need a official one

**Comment by LNJ2** [comment]
@JBBgameich 
1.) If there is no good icon to select until next weekend, we will have a problem...
2.) I would say for 5 people we don't need a poll, github is enough

**Comment by JBBgameich** [comment]
If we haven't got some new we can select a existent one, and the poll don't need's to be on another website, just a question on github "which icon do you like best?"

**Comment by IlyaBizyaev** [comment]
OK, I think I'll find time to make the final version till the next weekend.That should be for the name "Kaidan", right?
