### ISSUE TITLE
Shiny new icon

### ISSUE THREAD

**Issue by IlyaBizyaev** [KaidanIM/Kaidan#62]
Hello! :)
I thought Kaidan icon can be improved a bit and created this one:
![kaidan](https://cloud.githubusercontent.com/assets/11175213/22694208/b7086ac8-ed5f-11e6-9b9f-8ae4d41a781d.png)
Here is the SVG source:  [kaidan.svg.zip](https://github.com/KaidanIM/Kaidan/files/757853/kaidan.svg.zip)

**Comment by LNJ2** [comment]
This definitely looks better than the current one. But I'm not sure about the lines + the ツ. Both look good but not combined. @JBBgameich @MRZA-MRZA - Do you think so, too?

**Comment by JBBgameich** [comment]
I like your new logo, and I don't have a problem with the text lines, as they have a similar color to the background. They remind me a little bit to an old android SMS app logo :D

**Comment by MRZA-MRZA** [comment]
Looks like a jelly blob :D

**Comment by LNJ2** [comment]
^^ "Confused", but it's ok (better than the current one)!
