### ISSUE TITLE
Support SailfishOS

### ISSUE THREAD

**Issue by MRZA-MRZA** [KaidanIM/Kaidan#9]
As I'm going to work on SailfishOS version of Kaidan I wonder how we should handle SailfishOS specific changes, e. g. in qml files.

For SailfishOS there is need of rpm spec file and modified project file. There also maybe other changes.

What is the best way to avoid breaking things, incompatibility and other mess?

**Comment by LNJ2** [comment]
As I know, you can just add SFOS/Android/...-specific code to C++ and also in QML. And of course you can add SFOS-specific changes in the project file (as here for android: https://github.com/KaidanIM/Kaidan/blob/master/app/resources/deployment.pri).

In C++ you can use:
```c++
#ifdef SFOS
        std::cout << "Yeah SFOS!";
#endif
```

**Comment by LNJ2** [comment]
> For SailfishOS there is need of rpm spec file...

I think that can be putted into utils/sailfishos/... or utils/sfos/...

**Comment by MRZA-MRZA** [comment]
Well. It's possible to use preprocessor in C++, but what about QML. I assume that QML files will be heavily modified according to SailfishOS's Look&Feel. Also I have no idea how to distinguish SailfishOS from Linux in .pri file.

**Comment by JBBgameich** [comment]
The QML files will only have to be modified if you wan't to youse sailfish's silica instead of our cross-platform kirigami, I think we will manage building it for sailfish OS. I think we only need to add sailfish API specific things like file open menu or similar, if sailfish needs some.

**Comment by MRZA-MRZA** [comment]
I'm in doubt that it's possible to use Kirigami on SailfishOS because SailfishOS apps heavily rely on Silica. Kirigami doesn't officially support SailfishOS.
I'd like @geobra to write a comment so we can decide.

**Comment by JBBgameich** [comment]
Kirigami requires at least Qt 5.6, so we could support all sailfish OS versions which include at least 5.6. Kirigami2, which uses QtQuick.Controls 2, needs at least Qt 5.7. Notmart is working on a breeze theme for QtQuick.Controls 2, but as long as we use QtQuick.Controls 2.0, things like buttons and similar should look like the platform theme on Sailfish OS also. I think later when we switch to Controls 2, we could maybe simply use for example the Material or Default theme of QtQuick.Controls 2 on all platforms, so kaidan would look identical everywhere

**Comment by LNJ2** [comment]
KaidanSF has now a Hello World GUI, we can create a Silica GUI there. So I'm closing this.
